- hosts: "*"
  become: yes

  pre_tasks:
    - name: Sprawdzanie miejsca na dysku
      shell: df -h
      register: check_storage_space_before

    - name: ilosc pozostalego miejsca na dysku
      debug:
        msg: "{{ check_storage_space_before.stdout_lines }}"

    - name: usuwanie nieuzywanych paczek
      command: apt-get -y autoremove
      register: apt_autoremove_output

    - name: paczki do usuniecia
      debug:
        msg: "{{ apt_autoremove_output.stdout_lines }}"

    - name: odswiezenie repozytorium
      apt:
       update_cache: yes

    - name: lista paczek do aktualizacji
      command: apt list --upgradable
      register: updates

    - debug: var=updates.stdout_lines

    - name: Zniszczenie calej ludzkosci
      pause:
        prompt: Potwierdz prosze ze na pewno chcesz usunac cala ludzkosc! Sprawdz wczesniejsze dane zanim potwierdzisz enterem! Enter aby kontynuowac masowa zaglade. Ctrl+c aby przerwać usuwanie ludzkosci.
      register: confirm_delete

  tasks:
    - name: aktualizacja repozytorium oraz zainstalowanych paczek
      apt:
        update_cache: yes
        upgrade: 'yes'

    - name: weryfikacja miejsca na dysku po aktualizacji
      shell: df -h
      register: check_storage_space_after

    - name: miejsce na dysku po aktualizacji
      debug:
        msg: "{{ check_storage_space_after.stdout_lines }}"

    - name: Sprawdzam czy serwer wymaga aktualizacji
      register: reboot_required_file
      stat: path=/var/run/reboot-required get_md5=no

    - name: restart jesli kernel byl aktualizowany
      reboot:
        msg: "Reboot initiated by Ansible for kernel updates"
        connect_timeout: 5
        reboot_timeout: 300
        pre_reboot_delay: 0
        post_reboot_delay: 30
        test_command: uptime
      when: reboot_required_file.stat.exists
