- name: Create New User
  hosts: ubuntu
  become: true
  gather_facts: false
  vars:
    username: arvelinger
    userpass: Metalord1^
  tasks:
    - name: Create User
      ansible.builtin.user:
        name: "{{ username }}"
        state: present
        shell: /bin/bash
        password: "{{ userpass | password_hash('sha512') }}"
        update_password: on_create
        groups: sudo
        append: yes

    - name: Deploy SSH Public Key
      ansible.posix.authorized_key:
        user: "{{ username }}"
        state: present
        key: "{{ lookup('file', '/home/{{ username }}/.ssh/id_rsa.pub') }}"

    - name: set up authorized keys for the arvelinger user
      authorized_key: user=arvelinger key="{{item}}"
      with_file:
        - ~/.ssh/id_rsa.pub

    - name: allow 'arvelinger' to use sudo without needing a password
      lineinfile:
        dest: /etc/sudoers
        line: 'arvelinger ALL=(ALL) NOPASSWD: ALL'
        validate: 'visudo -cf %s'
