- name: Create New User
  hosts: ubuntu
  become: true
  gather_facts: false
  vars:
    username: [wstaw tu swojego usera bez nawiasow]
    userpass: [wstaw tu swojeg haslo bez nawiasow]
  tasks:
    - name: Tworzenie uzytkownika
      ansible.builtin.user:
        name: "{{ username }}"
        state: present
        shell: /bin/bash
        password: "{{ userpass | password_hash('sha512') }}"
        update_password: on_create
        groups: sudo
        append: yes

    - name: Dodawanie publicznego klucza SSH
      ansible.posix.authorized_key:
        user: "{{ username }}"
        state: present
        key: "{{ lookup('file', '/home/{{ username }}/.ssh/id_rsa.pub') }}"

    - name: set up authorized keys for the "{{ username }}" user
      authorized_key: user="{{ username }}" key="{{item}}"
      with_file:
        - ~/.ssh/id_rsa.pub

    - name: Uzywanie sudo bez podawania hasla dla "{{ username }}"
      lineinfile:
        dest: /etc/sudoers
        line: '"{{ username }}" ALL=(ALL) NOPASSWD: ALL'
        validate: 'visudo -cf %s'
