- name: install latest zsh on all hosts
  hosts: "*"
  become: true
  tasks:
    - name: install zsh
      apt:
        name: zsh
        state: present
        update_cache: yes

    - name: install zsh-syntax-highlighting
      apt:
        name: zsh-syntax-highlighting
        state: present
        update_cache: yes

    - name: install zsh-autosuggestions
      apt:
        name: zsh-autosuggestions
        state: present
        update_cache: yes

    - name: install curl
      apt:
        name: curl
        state: present
        update_cache: yes

    - name: install wget
      apt:
        name: wget
        state: present
        update_cache: yes

    - name: install git
      apt:
        name: git
        state: present
        update_cache: yes

    - name: Check if .zshrc exists
      stat:
        path: ~/.zshrc
      register: stat_rc_result

    - name: Check if .oh-my-zsh exists
      stat:
        path: ~/.oh-my-zsh
      register: stat_oh_my_zsh_result

    - name: Cloning  oh-my-zsh
      git:
        repo=https://github.com/robbyrussell/oh-my-zsh
        dest=~/.oh-my-zsh
      when: not stat_oh_my_zsh_result.stat.exists

    - name: Creating new ~/.zshrc
      copy:
        src=~/.oh-my-zsh/templates/zshrc.zsh-template
        dest=~/.zshrc
      when: not stat_rc_result.stat.exists

